### ISSUE TITLE
Windows can't find kanobu executable after installing

### ISSUE THREAD

**Issue by 0x0bloodyknight** [jDan735/kanobu#16]
## Expected Behavior
Kanobu main menu

## Current Behavior

`Traceback (most recent call last):
  File "C:\Users\nik57\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\Scripts\kanobu-script.py", line 11, in <module>
    load_entry_point('kanobu==0.1.2', 'console_scripts', 'kanobu')()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2032.0_x64__qbz5n2kfra8p0\lib\site-packages\pkg_resources\__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2032.0_x64__qbz5n2kfra8p0\lib\site-packages\pkg_resources\__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2032.0_x64__qbz5n2kfra8p0\lib\site-packages\pkg_resources\__init__.py", line 2443, in load
    return self.resolve()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2032.0_x64__qbz5n2kfra8p0\lib\site-packages\pkg_resources\__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'kanobu'`

## Steps to Reproduce

1. pip install kanobu
2. find kanobu.exe
3. run kanobu.exe in cmd
4.

## Context (Environment)
OS: Microsoft Windows [Version 10.0.19041.264]
Python: Python 3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 11:52:54) [MSC v.1900 64 bit (AMD64)] on win32
## Detailed Description
First of all, I run `pip install kanobu`, is succeeds, then I restart my cmd and run `kanobu` and get `'kanobu' is not recognized as an internal or external command,
operable program or batch file.`

**Comment by jDan735** [comment]
Upgrade python
