### ISSUE TITLE
Crash when choosing ukrainian language

### ISSUE THREAD

**Issue by 0x0bloodyknight** [jDan735/kanobu#6]
### Steps to reproduce
- run the ropasci.py
- type ua and hit Enter

### System info
os: Microsoft Windows [Version 10.0.19041.207] 
python: 3.7.7

### Full output
```
python3 ropasci.py
Your language? (de, en, ru, ua, em) ua
Traceback (most recent call last):
  File "C:\Users\nik57\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\speg\peg.py", line 20, in peg
    return p(r)
  File "C:\Users\nik57\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\speg\peg.py", line 74, in __call__
    return r(self, *args, **kw)
  File "C:\Users\nik57\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\cson\parser.py", line 294, in _p_root
    p(p.eof)
  File "C:\Users\nik57\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\speg\peg.py", line 74, in __call__
    return r(self, *args, **kw)
  File "C:\Users\nik57\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\speg\peg.py", line 86, in eof
    p.error()
  File "C:\Users\nik57\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\speg\peg.py", line 93, in error
    raise _UnexpectedError(st, expr)
speg.peg._UnexpectedError: (<speg.peg._PegState object at 0x0000021FEA9AD988>, None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ropasci.py", line 33, in <module>
    locale = cson.load(locale_file)
  File "C:\Users\nik57\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\cson\parser.py", line 10, in load
    return loads(fin.read())
  File "C:\Users\nik57\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\cson\parser.py", line 17, in loads
    return peg(s.replace('\r\n', '\n'), _p_root)
  File "C:\Users\nik57\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\speg\peg.py", line 24, in peg
    raise ParseError(err.msg, s, offset, err.line, err.col)
speg.peg.ParseError: ("expected None, found 'argu'", 257, 12, 3)
```

**Comment by jDan735** [comment]
Fixed 0e5d985c7d6fdb0df96f16877b94f43e8db832dd
