### ISSUE TITLE
Not work kanobu start comand in Lubuntu 18.04 x86

### ISSUE THREAD

**Issue by jDan735** [jDan735/kanobu#9]
When i start kanobu:
```
daniel@VirtualBox:~/github/kanobu-module$ kanobu
```
I get:
```
Traceback (most recent call last):
  File "/usr/local/bin/kanobu", line 11, in <module>
    load_entry_point('kanobu==0.1.1', 'console_scripts', 'kanobu')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'kanobu'
```

**Comment by jDan735** [comment]
When I call kanobu via `python -m kanobu` program work

**Comment by jDan735** [comment]
Fixed
